#!/usr/bin/env python3
"""Build a standalone Kaggle submission agent from a trained checkpoint."""

import argparse
import base64
import pickle
from pathlib import Path
from string import Template

import numpy as np
import torch

from src.shared.constants import SHIP_BUCKET_RATIOS


def _serialize_weights(state_dict):
    weights = {}
    for key, tensor in state_dict.items():
        weights[key] = tensor.detach().cpu().numpy().astype(np.float32)
    return base64.b64encode(pickle.dumps(weights)).decode("ascii")


def _format_list(sequence):
    return "[" + ", ".join(repr(x) for x in sequence) + "]"


def _build_submission_code(weights_b64, env_cfg, candidate_count, hidden_size, ship_ratios):
    return Template('''#!/usr/bin/env python3
"""Standalone Kaggle Orbit Wars policy auto-generated by build_submission.py."""

import base64
import math
import pickle

import numpy as np

_WEIGHTS_B64 = """$weights_b64"""
CANDIDATE_COUNT = $candidate_count
HIDDEN_SIZE = $hidden_size
SHIP_BUCKET_RATIOS = $ship_ratios
ENV_CONFIG = {
    "board_size": $board_size,
    "episode_steps": $episode_steps,
    "candidate_count": $candidate_count,
    "max_planets": $max_planets,
    "max_ships": $max_ships,
    "max_production": $max_production,
}


def _load_weights():
    payload = base64.b64decode(_WEIGHTS_B64)
    return pickle.loads(payload)


def clamp(value, minimum, maximum):
    return max(min(value, maximum), minimum)


def normalize(value, scale):
    return float(value) / max(float(scale), 1.0)


def distance(x1, y1, x2, y2):
    return math.hypot(x2 - x1, y2 - y1)


def relu(x):
    return np.maximum(x, 0.0)


def linear_forward(x, weight, bias):
    return x.dot(weight.T) + bias


def mlp_forward(x, weights, prefix, layers=2):
    h = x
    for layer in range(layers):
        w = weights[f"{prefix}.{layer * 2}.weight"]
        b = weights[f"{prefix}.{layer * 2}.bias"]
        h = linear_forward(h, w, b)
        if layer < layers - 1:
            h = relu(h)
    return h


def _parse_planet(row):
    if isinstance(row, dict):
        return [
            int(row.get("id", 0)),
            int(row.get("owner", -1)),
            float(row.get("x", 0.0)),
            float(row.get("y", 0.0)),
            float(row.get("radius", 5.0)),
            int(row.get("ships", 0)),
            int(row.get("prod", row.get("production", 0))),
        ]
    if len(row) >= 7:
        return [
            int(row[0]),
            int(row[1]),
            float(row[2]),
            float(row[3]),
            float(row[4]),
            int(row[5]),
            int(row[6]),
        ]
    if len(row) == 6:
        return [
            int(row[0]),
            int(row[1]),
            float(row[2]),
            float(row[3]),
            float(row[4]),
            int(row[5]),
            0,
        ]
    raise ValueError("Unsupported planet row format")


def _parse_fleet(row):
    if isinstance(row, dict):
        return [
            int(row.get("id", 0)),
            int(row.get("owner", -1)),
            int(row.get("source", row.get("from_planet_id", -1))),
            float(row.get("x", 0.0)),
            float(row.get("y", 0.0)),
            float(row.get("vx", 0.0)),
            float(row.get("vy", 0.0)),
            int(row.get("ships", 0)),
        ]
    if len(row) >= 8:
        return [
            int(row[0]),
            int(row[1]),
            int(row[2]),
            float(row[3]),
            float(row[4]),
            float(row[5]),
            float(row[6]),
            int(row[7]),
        ]
    return [0, -1, -1, 0.0, 0.0, 0.0, 0.0, 0]


def build_candidates(source, planets):
    others = [p for p in planets if p[0] != source[0]]
    enemies = sorted([p for p in others if p[1] not in (-1, source[1])], key=lambda p: (distance(source[2], source[3], p[2], p[3]), p[0]))
    neutrals = sorted([p for p in others if p[1] == -1], key=lambda p: (distance(source[2], source[3], p[2], p[3]), p[0]))
    friendlies = sorted([p for p in others if p[1] == source[1]], key=lambda p: (distance(source[2], source[3], p[2], p[3]), p[0]))

    selected = []
    seen = set()
    for group in (enemies, neutrals, friendlies):
        for planet in group:
            if planet[0] in seen:
                continue
            seen.add(planet[0])
            selected.append(planet)
            if len(selected) >= ENV_CONFIG["candidate_count"] - 1:
                return selected
    return selected


def build_self_features(source, state, env_cfg):
    mine = [p for p in state["planets"] if p[1] == state["player"]]
    enemies = [p for p in state["planets"] if p[1] not in (-1, state["player"])]
    neutrals = [p for p in state["planets"] if p[1] == -1]
    my_fleets = [f for f in state.get("fleets", []) if f[1] == state["player"]]
    enemy_fleets = [f for f in state.get("fleets", []) if f[1] != state["player"]]
    total_ships = sum(p[5] for p in mine)
    total_enemy_ships = sum(p[5] for p in enemies)
    total_neutral_ships = sum(p[5] for p in neutrals)
    center_x = env_cfg["board_size"] / 2.0
    center_y = env_cfg["board_size"] / 2.0
    centrality = 1.0 - clamp(distance(source[2], source[3], center_x, center_y) / math.hypot(center_x, center_y), 0.0, 1.0)
    frontier_distance = env_cfg["board_size"]
    for other in enemies + neutrals:
        frontier_distance = min(frontier_distance, distance(source[2], source[3], other[2], other[3]))
    frontier_ratio = clamp(1.0 - frontier_distance / env_cfg["board_size"], 0.0, 1.0)
    incoming_friendly = sum(f[7] for f in my_fleets if distance(source[2], source[3], f[3], f[4]) < env_cfg["board_size"] * 0.5)
    incoming_enemy = sum(f[7] for f in enemy_fleets if distance(source[2], source[3], f[3], f[4]) < env_cfg["board_size"] * 0.5)

    return [
        normalize(source[2], env_cfg["board_size"]),
        normalize(source[3], env_cfg["board_size"]),
        normalize(source[5], env_cfg["max_ships"]),
        normalize(source[6], env_cfg["max_production"]),
        normalize(len(mine), env_cfg["max_planets"]),
        normalize(len(enemies), env_cfg["max_planets"]),
        normalize(len(neutrals), env_cfg["max_planets"]),
        normalize(total_ships, env_cfg["max_planets"] * env_cfg["max_ships"]),
        normalize(total_enemy_ships, env_cfg["max_planets"] * env_cfg["max_ships"]),
        normalize(total_neutral_ships, env_cfg["max_planets"] * env_cfg["max_ships"]),
        normalize(incoming_friendly, env_cfg["max_ships"]),
        normalize(incoming_enemy, env_cfg["max_ships"]),
        centrality,
        frontier_ratio,
        normalize(state["step"], env_cfg["episode_steps"]),
    ]


def build_candidate_features(source, candidates, state, env_cfg):
    features = [[0.0] * 19 for _ in range(env_cfg["candidate_count"])]
    mask = [False] * env_cfg["candidate_count"]
    ship_counts = [0] * env_cfg["candidate_count"]
    candidate_ids = [-1] * env_cfg["candidate_count"]
    mask[0] = True
    features[0][0] = 1.0

    my_fleets = [f for f in state.get("fleets", []) if f[1] == state["player"]]
    enemy_fleets = [f for f in state.get("fleets", []) if f[1] != state["player"]]
    source_ships = source[5]
    source_prod = source[6]

    for idx, target in enumerate(candidates, start=1):
        if idx >= env_cfg["candidate_count"]:
            break
        dx = target[2] - source[2]
        dy = target[3] - source[3]
        dist = distance(source[2], source[3], target[2], target[3])
        
        if target[1] == state["player"]:
            needed = 0
        else:
            needed = max(int(target[5]) + 1, 1)
        
        incoming_friendly = sum(f[7] for f in my_fleets if distance(target[2], target[3], f[3], f[4]) < env_cfg["board_size"] * 0.5)
        incoming_enemy = sum(f[7] for f in enemy_fleets if distance(target[2], target[3], f[3], f[4]) < env_cfg["board_size"] * 0.5)
        local_friendly = sum(p[5] for p in state["planets"] if p[1] == state["player"] and distance(target[2], target[3], p[2], p[3]) < env_cfg["board_size"] * 0.3)
        local_enemy = sum(p[5] for p in state["planets"] if p[1] not in (-1, state["player"]) and distance(target[2], target[3], p[2], p[3]) < env_cfg["board_size"] * 0.3)
        vulnerability = clamp(((source_ships + source_prod) - (target[5] + target[6])) / env_cfg["max_ships"], -1.0, 1.0)
        pressure = clamp((local_enemy - local_friendly) / env_cfg["max_ships"], -1.0, 1.0)

        features[idx] = [
            0.0,
            1.0 if target[1] == -1 else 0.0,
            1.0 if target[1] == state["player"] else 0.0,
            1.0 if target[1] not in (-1, state["player"]) else 0.0,
            normalize(target[2], env_cfg["board_size"]),
            normalize(target[3], env_cfg["board_size"]),
            normalize(dx, env_cfg["board_size"]),
            normalize(dy, env_cfg["board_size"]),
            clamp(dist / env_cfg["board_size"], 0.0, 1.0),
            normalize(target[5], env_cfg["max_ships"]),
            normalize(target[6], env_cfg["max_production"]),
            normalize(source_ships, env_cfg["max_ships"]),
            normalize(source_prod, env_cfg["max_production"]),
            normalize(target[5], max(source_ships, 1)),
            normalize(target[6], max(source_prod, 1)),
            normalize(incoming_friendly, env_cfg["max_ships"]),
            normalize(incoming_enemy, env_cfg["max_ships"]),
            vulnerability,
            pressure,
        ]
        ship_counts[idx] = needed
        candidate_ids[idx] = target[0]
        mask[idx] = True

    return features, mask, ship_counts, candidate_ids


def build_global_features(state, env_cfg):
    planets = state["planets"]
    mine = [p for p in planets if p[1] == state["player"]]
    enemies = [p for p in planets if p[1] not in (-1, state["player"])]
    neutrals = [p for p in planets if p[1] == -1]
    my_fleets = [f for f in state.get("fleets", []) if f[1] == state["player"]]
    enemy_fleets = [f for f in state.get("fleets", []) if f[1] != state["player"]]
    total_ship_scale = env_cfg["max_planets"] * env_cfg["max_ships"]
    total_prod_scale = env_cfg["max_planets"] * env_cfg["max_production"]
    nearest_enemy = env_cfg["board_size"]
    nearest_neutral = env_cfg["board_size"]
    for p in enemies:
        nearest_enemy = min(nearest_enemy, distance(0.0, 0.0, p[2], p[3]))
    for p in neutrals:
        nearest_neutral = min(nearest_neutral, distance(0.0, 0.0, p[2], p[3]))
    return [
        normalize(state["step"], env_cfg["episode_steps"]),
        normalize(len(mine), env_cfg["max_planets"]),
        normalize(len(enemies), env_cfg["max_planets"]),
        normalize(len(neutrals), env_cfg["max_planets"]),
        normalize(sum(p[5] for p in mine), total_ship_scale),
        normalize(sum(p[5] for p in enemies), total_ship_scale),
        normalize(sum(p[5] for p in neutrals), total_ship_scale),
        normalize(sum(p[6] for p in mine), total_prod_scale),
        normalize(sum(p[6] for p in enemies), total_prod_scale),
        normalize(sum(f[7] for f in my_fleets), total_ship_scale),
        normalize(sum(f[7] for f in enemy_fleets), total_ship_scale),
        clamp(nearest_enemy / env_cfg["board_size"], 0.0, 1.0),
        clamp(nearest_neutral / env_cfg["board_size"], 0.0, 1.0),
    ]


def encode_turn(obs, env_cfg):
    state = {
        "player": int(obs.get("player", 0)) if isinstance(obs, dict) else int(getattr(obs, "player", 0)),
        "step": int(obs.get("step", 0)) if isinstance(obs, dict) else int(getattr(obs, "step", 0)),
        "planets": [],
        "fleets": [],
    }
    raw_planets = obs.get("planets", []) if isinstance(obs, dict) else getattr(obs, "planets", [])
    raw_fleets = obs.get("fleets", []) if isinstance(obs, dict) else getattr(obs, "fleets", [])

    for row in raw_planets:
        state["planets"].append(_parse_planet(row))
    for row in raw_fleets:
        state["fleets"].append(_parse_fleet(row))

    sources = [planet for planet in state["planets"] if planet[1] == state["player"]]
    if not sources:
        return [], [], [], [], []

    self_features = []
    candidate_features = []
    global_features = []
    candidate_mask = []
    contexts = []
    global_feat = build_global_features(state, env_cfg)

    for source in sources:
        candidates = build_candidates(source, state["planets"])
        cand_features, cand_mask, ship_counts, candidate_ids = build_candidate_features(source, candidates, state, env_cfg)
        self_features.append(build_self_features(source, state, env_cfg))
        candidate_features.append(cand_features)
        candidate_mask.append(cand_mask)
        contexts.append((source[0], candidate_ids, ship_counts, source[5]))
        global_features.append(global_feat)

    return (
        np.asarray(self_features, dtype=np.float32),
        np.asarray(candidate_features, dtype=np.float32).reshape(len(self_features), env_cfg["candidate_count"], -1),
        np.asarray(global_features, dtype=np.float32),
        np.asarray(candidate_mask, dtype=np.float32),
        contexts,
    )


def policy_forward(self_features, candidate_features, global_features, candidate_mask, weights):
    self_h = mlp_forward(self_features, weights, "self_encoder")
    candidate_h = mlp_forward(candidate_features.reshape(-1, candidate_features.shape[-1]), weights, "candidate_encoder")
    candidate_h = candidate_h.reshape(candidate_features.shape)
    global_h = mlp_forward(global_features, weights, "global_encoder")

    expanded_self = np.repeat(self_h[:, np.newaxis, :], CANDIDATE_COUNT, axis=1)
    expanded_global = np.repeat(global_h[:, np.newaxis, :], CANDIDATE_COUNT, axis=1)
    joint = np.concatenate([expanded_self, expanded_global, candidate_h], axis=-1)

    joint_flat = joint.reshape(-1, joint.shape[-1])
    t_h = relu(linear_forward(joint_flat, weights["target_head.0.weight"], weights["target_head.0.bias"]))
    logits = linear_forward(t_h, weights["target_head.2.weight"], weights["target_head.2.bias"]).reshape(self_features.shape[0], CANDIDATE_COUNT)
    logits = logits - 1e9 * (1.0 - candidate_mask)

    pooled = candidate_h.mean(axis=1)
    ship_input = np.concatenate([self_h, global_h, pooled], axis=-1)
    s_h = relu(linear_forward(ship_input, weights["ship_head.0.weight"], weights["ship_head.0.bias"]))
    ship_logits = linear_forward(s_h, weights["ship_head.2.weight"], weights["ship_head.2.bias"]).reshape(self_features.shape[0], $ship_ratio_count)

    return logits, ship_logits


def bucket_to_ships(source_ships, bucket_index):
    if source_ships <= 0 or bucket_index < 0 or bucket_index >= len(SHIP_BUCKET_RATIOS):
        return 0
    ratio = SHIP_BUCKET_RATIOS[bucket_index]
    return int(max(0, round(source_ships * ratio)))


_WEIGHTS = None


def agent(obs, config=None):
    global _WEIGHTS
    if _WEIGHTS is None:
        _WEIGHTS = _load_weights()

    raw_planets = obs.get("planets", []) if isinstance(obs, dict) else getattr(obs, "planets", [])
    positions = {}
    for row in raw_planets:
        if isinstance(row, dict):
            positions[int(row.get("id", 0))] = (float(row.get("x", 0.0)), float(row.get("y", 0.0)))
        else:
            positions[int(row[0])] = (float(row[2]), float(row[3]))

    result = encode_turn(obs, ENV_CONFIG)
    self_features, candidate_features, global_features, candidate_mask, contexts = result
    if len(self_features) == 0:
        return []

    logits, ship_logits = policy_forward(self_features, candidate_features, global_features, candidate_mask, _WEIGHTS)

    moves = []
    for row_idx in range(len(contexts)):
        source_id, candidate_ids, ship_counts, source_ships = contexts[row_idx]
        target_idx = int(logits[row_idx].argmax())
        ship_idx = int(ship_logits[row_idx].argmax())
        if target_idx <= 0 or target_idx >= len(candidate_ids):
            continue
        target_id = candidate_ids[target_idx]
        if target_id < 0:
            continue
        ships = bucket_to_ships(source_ships, ship_idx)
        if ships <= 0:
            continue
        src_pos = positions.get(source_id)
        tgt_pos = positions.get(target_id)
        if src_pos is None or tgt_pos is None:
            continue
        angle = math.atan2(tgt_pos[1] - src_pos[1], tgt_pos[0] - src_pos[0])
        moves.append([source_id, angle, ships])
    return moves
''').substitute(
        weights_b64=weights_b64,
        candidate_count=candidate_count,
        hidden_size=hidden_size,
        ship_ratios=_format_list(ship_ratios),
        ship_ratio_count=len(ship_ratios),
        board_size=env_cfg["board_size"],
        episode_steps=env_cfg["episode_steps"],
        max_planets=env_cfg["max_planets"],
        max_ships=env_cfg["max_ships"],
        max_production=env_cfg["max_production"],
    )


def export_submission(checkpoint_path, output_path):
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    cfg = checkpoint.get("config")
    if cfg is None:
        raise ValueError("Checkpoint does not contain config metadata")
    weights_b64 = _serialize_weights(checkpoint["policy"])
    env_cfg = {
        "board_size": cfg.env.board_size,
        "episode_steps": cfg.env.episode_steps,
        "candidate_count": cfg.env.candidate_count,
        "max_planets": cfg.env.max_planets,
        "max_ships": cfg.env.max_ships,
        "max_production": cfg.env.max_production,
    }
    code = _build_submission_code(weights_b64, env_cfg, cfg.env.candidate_count, cfg.model.hidden_size, SHIP_BUCKET_RATIOS)
    Path(output_path).write_text(code, encoding="utf-8")
    print(f"Built submission agent: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build standalone Kaggle submission agent")
    parser.add_argument("--checkpoint", required=True, help="Path to trained checkpoint")
    parser.add_argument("--output", default="agents/submission/submission.py", help="Output standalone agent file")
    args = parser.parse_args()
    export_submission(args.checkpoint, args.output)
