#!/usr/bin/env python3
"""Export trained RL agent as a numpy-only .py file for Kaggle submission."""

import sys
from pathlib import Path
import torch
import numpy as np
import pickle
import base64
import io


def export_numpy_agent(checkpoint_path: str, output_path: str):
    """Export trained agent as a numpy-only Python file for Kaggle."""

    # Load checkpoint
    device = torch.device("cpu")
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)

    # Get config from checkpoint
    if "config" in checkpoint:
        cfg = checkpoint["config"]
        hidden_size = cfg.model.hidden_size
        candidate_count = cfg.env.candidate_count
    else:
        hidden_size = 128
        candidate_count = 15

    state_dict = checkpoint["policy"]

    # Convert all weights to numpy
    numpy_weights = {}
    for key, value in state_dict.items():
        if isinstance(value, torch.Tensor):
            numpy_weights[key] = value.detach().numpy()
        else:
            numpy_weights[key] = np.array(value)

    # Pickle the weights and base64 encode
    pickled = pickle.dumps(numpy_weights)
    weights_b64 = base64.b64encode(pickled).decode('utf-8')

    print(f"Model: hidden_size={hidden_size}, candidate_count={candidate_count}")
    print(f"Weights encoded: {len(weights_b64)} bytes (base64)")

    # Create standalone numpy-only agent file
    standalone_code = f'''#!/usr/bin/env python3
"""Standalone RL Agent for Kaggle Orbit Wars Competition.
Numpy-only version - no PyTorch dependency.
Auto-generated by export_for_kaggle.py
"""

import numpy as np
import math
import base64
import io
import pickle


# ---- Model Weights ----
_WEIGHTS_B64 = "{weights_b64}"
_weights = None

def get_weights():
    global _weights
    if _weights is None:
        try:
            data = base64.b64decode(_WEIGHTS_B64)
            _weights = pickle.loads(data)
        except Exception as e:
            print(f"Error loading weights: {{e}}")
            raise
    return _weights


# ---- Helper Functions ----
def relu(x):
    return np.maximum(0, x)

def linear_forward(x, weight, bias):
    return np.dot(x, weight.T) + bias

def mlp_forward(x, weights, prefix, input_dim, hidden_size, num_layers=2):
    h = x
    for i in range(num_layers):
        w = weights[f"{{prefix}}.{{i*2}}.weight"]
        b = weights[f"{{prefix}}.{{i*2}}.bias"]
        h = linear_forward(h, w, b)
        if i < num_layers - 1:
            h = relu(h)
    return h


def policy_forward(self_features, candidate_features, global_features, candidate_mask, weights, candidate_count, hidden_size=128):
    batch_size = self_features.shape[0]
    
    # Encode features
    self_h = mlp_forward(self_features, weights, "self_encoder", 10, hidden_size, 2)
    candidate_h = mlp_forward(candidate_features, weights, "candidate_encoder", 13, hidden_size, 2)
    global_h = mlp_forward(global_features, weights, "global_encoder", 8, hidden_size, 2)
    
    # Expand
    expanded_self = np.repeat(self_h[:, np.newaxis, :], candidate_count, axis=1)
    expanded_global = np.repeat(global_h[:, np.newaxis, :], candidate_count, axis=1)
    
    candidate_h_reshaped = candidate_h.reshape(batch_size, candidate_count, -1)
    joint = np.concatenate([expanded_self, expanded_global, candidate_h_reshaped], axis=-1)
    
    # Target head (2 layers)
    joint_2d = joint.reshape(-1, joint.shape[-1])
    t_w1 = weights["target_head.0.weight"]
    t_b1 = weights["target_head.0.bias"]
    t_h = relu(linear_forward(joint_2d, t_w1, t_b1))
    t_w2 = weights["target_head.2.weight"]
    t_b2 = weights["target_head.2.bias"]
    logits_2d = linear_forward(t_h, t_w2, t_b2)
    logits = logits_2d.reshape(batch_size, candidate_count)
    
    # Apply mask
    logits = logits - 1e9 * (1 - candidate_mask)
    
    # Get action (argmax)
    actions = np.argmax(logits, axis=1)
    
    return actions


# ---- Feature Extraction ----
def encode_turn(obs, candidate_count={candidate_count}):
    planets_data = obs.get("planets", [])
    my_id = obs.get("player", 0)
    turn = obs.get("turn", 0)
    
    planets = []
    for p in planets_data:
        planets.append({{"id": p[0], "owner": p[1], "x": p[2], "y": p[3],
                        "radius": p[4], "ships": p[5], "production": p[6]}})
    
    my_planets = [p for p in planets if p["owner"] == my_id]
    planet_by_id = {{p["id"]: p for p in planets}}
    
    self_features_list = []
    candidate_features_list = []
    global_features_list = []
    planet_ids = []
    candidate_lists = []
    
    for planet in my_planets:
        total_ships = sum(p["ships"] for p in my_planets)
        total_prod = sum(p["production"] for p in my_planets)
        enemy_ships = sum(p["ships"] for p in planets if p["owner"] not in (0, my_id))
        neutral_ships = sum(p["ships"] for p in planets if p["owner"] == 0)
        
        self_feat = [
            planet["ships"] / 100.0,
            planet["production"] / 10.0,
            len(my_planets) / 20.0,
            total_ships / 500.0,
            total_prod / 50.0,
            turn / 500.0,
            enemy_ships / 500.0,
            neutral_ships / 500.0,
            len(planet_by_id) / 30.0,
            (planet["ships"] / max(total_ships, 1)) if total_ships > 0 else 0.0,
        ]
        self_features_list.append(self_feat)
        planet_ids.append(planet["id"])
        
        candidates = [p for p in planets if p["id"] != planet["id"]][:candidate_count]
        candidate_lists.append([c["id"] for c in candidates])
        
        for cand in candidates:
            dist = math.sqrt((planet["x"] - cand["x"])**2 + (planet["y"] - cand["y"])**2)
            max_dist = math.sqrt(2) * 100
            cand_feat = [
                cand["id"] / 30.0,
                cand["ships"] / 100.0,
                cand["production"] / 10.0,
                (cand["owner"] == my_id) * 1.0,
                (cand["owner"] == 0) * 1.0,
                (cand["owner"] not in (0, my_id)) * 1.0,
                dist / max_dist,
                planet["ships"] / 100.0,
                cand["production"] / max(planet["production"], 1) if planet["production"] > 0 else 0.0,
                (cand["ships"] > planet["ships"]) * 1.0,
                (cand["ships"] <= planet["ships"] * 1.5) * 1.0,
                (cand["owner"] == 0 and cand["ships"] == 0) * 1.0,
                (cand["production"] >= 3) * 1.0,
            ]
            candidate_features_list.append(cand_feat)
    
    while len(candidate_features_list) < len(self_features_list) * candidate_count:
        candidate_features_list.append([0.0] * 13)
    
    for _ in my_planets:
        total_ships = sum(p["ships"] for p in my_planets)
        total_prod = sum(p["production"] for p in my_planets)
        enemy_ships = sum(p["ships"] for p in planets if p["owner"] not in (0, my_id))
        neutral_ships = sum(p["ships"] for p in planets if p["owner"] == 0)
        
        global_feat = [
            turn / 500.0,
            len(my_planets) / 20.0,
            total_ships / 500.0,
            total_prod / 50.0,
            enemy_ships / 500.0,
            neutral_ships / 500.0,
            len(planet_by_id) / 30.0,
            len(obs.get("fleets", [])) / 100.0,
        ]
        global_features_list.append(global_feat)
    
    candidate_mask = []
    for i in range(len(planet_ids)):
        for j in range(candidate_count):
            candidate_mask.append(1.0 if j < len(candidate_lists[i]) else 0.0)
    
    return (
        np.array(self_features_list, dtype=np.float32),
        np.array(candidate_features_list, dtype=np.float32),
        np.array(global_features_list, dtype=np.float32),
        np.array(candidate_mask, dtype=np.float32).reshape(-1, candidate_count),
        planet_ids,
        candidate_lists,
    )


# ---- Global agent function (required by Kaggle) ----
def agent(obs):
    """Kaggle entry point - returns actions in format [[planet_id, angle, ships], ...]"""
    try:
        weights = get_weights()
        self_feat, cand_feat, global_feat, cand_mask, planet_ids, cand_lists = encode_turn(obs, {candidate_count})
        
        if len(self_feat) == 0:
            return []
        
        actions = policy_forward(self_feat, cand_feat, global_feat, cand_mask, weights, {candidate_count}, {hidden_size})
        
        moves = []
        planets_dict = {{p[0]: p for p in obs.get("planets", [])}}
        
        for i, (planet_id, action_idx) in enumerate(zip(planet_ids, actions)):
            if action_idx < len(cand_lists[i]):
                target_id = cand_lists[i][action_idx]
                target_planet = planets_dict.get(target_id)
                my_planet = planets_dict.get(planet_id)
                
                if target_planet and my_planet:
                    dx = target_planet[2] - my_planet[2]
                    dy = target_planet[3] - my_planet[3]
                    angle = math.atan2(dy, dx)
                    ships = min(my_planet[5], target_planet[5] + 5)
                    if ships > 0:
                        moves.append([planet_id, angle, int(ships)])
        
        return moves
    except Exception as e:
        print(f"Error in agent: {{e}}")
        import traceback
        traceback.print_exc()
        return []


if __name__ == "__main__":
    print("Kaggle Numpy-Only Agent loaded successfully!")
    print(f"Model hidden size: {hidden_size}")
    print(f"Candidate count: {candidate_count}")
    print("No PyTorch dependency - should work in Kaggle!")
'''

    # Write output file
    with open(output_path, 'w') as f:
        f.write(standalone_code)

    print(f"Numpy-only agent exported to: {output_path}")
    print(f"File size: {Path(output_path).stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Export numpy-only RL agent for Kaggle")
    parser.add_argument("--checkpoint", type=str, default="models/rl/orbit_wars_ppo/ckpt_last.pt",
                        help="Path to checkpoint file")
    parser.add_argument("--output", type=str, default="main.py",
                        help="Output path for the agent .py file")

    args = parser.parse_args()

    if not Path(args.checkpoint).exists():
        print(f"Error: Checkpoint not found at {args.checkpoint}")
        sys.exit(1)

    export_numpy_agent(args.checkpoint, args.output)
